# Generated by Django 6.1.2 on 2026-10-09 15:31

import apps.categories.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.categories.models.upload_image_path, verbose_name='تصویر شاخص'),
        ),
    ]
