# Generated by Django 6.1.2 on 2026-10-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_business_views_count_alter_business_created_at_and_more'),
        ('categories', '0002_alter_category_options_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('item_type', models.CharField(choices=[('product', 'کالا'), ('service', 'خدمت')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='categories.category')),
            ],
            options={
                'unique_together': {('title', 'item_type')},
            },
        ),
        migrations.CreateModel(
            name='BusinessCatalogOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('custom_description', models.TextField(blank=True)),
                ('purchase_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='businesses.business')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_offers', to='catalog.centralcatalogitem')),
            ],
        ),
    ]
